#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     accel,          sensorI2CCustom)
#pragma config(Sensor, S3,     GYRO,           sensorAnalogInactive)
#pragma config(Sensor, S4,     IR,             sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "beaconDetection.h"
#include "TurnAngle.h"
#include <JoystickDriver.c>
#include "Collision.h"

task main()
{

	//Wait for the start command//
	waitForStart();
	motor[elevatorElevator] = -60;
	wait1Msec(750);
	motor[elevatorElevator] = 0;
	//Start getHeading.h//
	HTGYROstartCal(GYRO);
	StartTask(getHeading);

	//Move forward until it sees the beacon or until 2.5 sec is up//
	motor[motorD] = -50;
	motor[motorE] = -50;
	motor[motorA] = -50;
	motor[motorB] = -50;
	time1[T3] = 0;

	while (atBeacon() == false && time1[T3] < 2500)
	{
		wait1Msec(2);
	}

	//Turn 90 to the right//
	TurnAngle(90, false);

	///////////////////////

	//Get momentum for Collision.h to work//
	motor[motorA] = -50;
	motor[motorD] = -50;
	motor[motorE] = -50;
	motor[motorB] = -50;

	wait1Msec(750);

	motor[motorA] = 0;
	motor[motorD] = 0;
	motor[motorE] = 0;
	motor[motorB] = 0;

	//Move forward for utill it hits//
	StartTask(Collision);
	wait1Msec(250);
	Set = -44;
	while(movement != 2)
	{
		motor[motorA] = 50;
		motor[motorD] = 50;
		motor[motorE] = 50;
		motor[motorB] = 50;
		wait1Msec(10);
	}

	motor[motorA] = 0;
	motor[motorD] = 0;
	motor[motorE] = 0;
	motor[motorB] = 0;
	PlaySound(soundBeepBeep);
	StopTask(Collision);

	//Move the block claw until 600 degrees//
	nMotorEncoder[motorC] = 0;
	while(abs(nMotorEncoder[motorC]) <= 1000) //540
	{
		motor[motorC] = 100;
	}

wait1Msec(250);

	//Move backward for 1 sec//
	motor[motorD] = -50;
	motor[motorE] = -50;
	motor[motorA] = -50;
	motor[motorB] = -50;

	wait1Msec(1000);

	motor[motorD] = 0;
	motor[motorE] = 0;
	motor[motorA] = 0;
	motor[motorB] = 0;

	StopAllTasks();

}
