#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     driveLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     driveLifter,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     elevatorElevator, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    leftGrabber,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    flipper,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    rightGrabber,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_4,    rightHanger,          tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    leftHanger,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    driveLock,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
* teleop.c
* This file is part of Teleop
*
* Copyright (C) 2013 - EMC Squirrled
*
* Teleop is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of th e License, or
* (at your option) any later version.
*
* Teleop is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with Teleop; if not, write to the Free Software
* Foundation, Inc., 51 Franklin St, Fifth Floor,
* Boston, MA  02110-1301  USA
*/


/* ===== INCLUDES ===== */

#include <JoystickDriver.c>

/* ===== DEFINES ===== */

/* Milliseconds between updates */
#define JOYSTICK_UPDATE_TIME 10
#define MOTOR_UPDATE_TIME 10

/* Joystick range to ignore */
#define DEADZONE 10

/* DPAD directional values */
#define DPAD_NONE -1
#define DPAD_UP 0
#define DPAD_DOWN 4
#define DPAD_LEFT 6
#define DPAD_RIGHT 2

/* This is not a #define, but we treat it like one
Used for file I/O */
word FILE_SIZE = 255;

/* ===== TASKS ===== */

task ReadJoystick1();
task ReadJoystick2();
task UpdateDriveMotors();
task UpdateManipulators();
task Debug();

/* ===== STRUCTURES ===== */

/* Defines the different drive modes. The specific numbers are also codes for the run control file */
typedef enum {
	TNK_LIN = 1,
	TNK_EXP = 0,
	TNK_LOW = 2,
	ARC_LIN = 4,
	ARC_EXP = 3,
	ARC_LOW = 5,
} mode;

/* Defines which side of the robot we are talking about */
typedef enum {
	LEFT,
	RIGHT,
} side;

/* Defines a motor */
typedef struct {
	signed byte iPower;
} my_motor;

/* Defines our robot */
typedef struct {
	my_motor oLeftMotor;
	my_motor oRightMotor;
	int grabberPower;
	int flipperPower;
	int elevatorPower;
	int elevatorRightPower;
	int elevatorLeftPower;
	int dispenserPower;
	int driveLifterPower;
	bool locked;
	bool hooks;
	mode oMode;
} robot;

/* ==== FUNCTIONS ===== */

void vInitializeRobot(void);
int iJoyToPower(side theSide);

/* ===== GLOBALS === */

/* Create a robot from the above template */
robot oRobot;

/* ===== CODE ===== */

/* Task Main -- Entry point of the code */
task main() {
	/* Initialize the robot and wait for the start of the match */
	vInitializeRobot();
	waitForStart();    //&&&&&&&&&&&&&&  	COMMENT OUT IF TESTING &&&&&&&&&&&&&&&&&&&&&&&//

	/* Start all tasks */
	StartTask(ReadJoystick1);
	StartTask(ReadJoystick2);
	StartTask(UpdateDriveMotors);
	StartTask(UpdateManipulators);
	StartTask(Debug);

	/* Do nothing, since the tasks do it all */
	while(1) wait10Msec(1000);
}

/* Set driving data from the first joystick */
task ReadJoystick1() {
	wait1Msec(3);
	/* Run forever */
	while(1) {
		/* Get the values from the joystick to use in the rest of this function */
		getJoystickSettings(joystick);
		motor[motorC] = 0;
	  if (joy2Btn(6)){
	  	motor[motorC] = -75;
	  }
	  if (joy2Btn(8)){
	  	motor[motorC] = 75;
	  }
		/* Overide the joystick values if the arrow buttons are being used */
		if (joystick.joy1_TopHat == DPAD_UP) {
			oRobot.oLeftMotor.iPower = 35;
			oRobot.oRightMotor.iPower = 35;
			} else if (joystick.joy1_TopHat == DPAD_DOWN) {
			oRobot.oLeftMotor.iPower = -35;
			oRobot.oRightMotor.iPower = -35;
			} else  if (joystick.joy1_TopHat == DPAD_LEFT) {
			oRobot.oLeftMotor.iPower = -70;
			oRobot.oRightMotor.iPower = 70;
			} else  if (joystick.joy1_TopHat == DPAD_RIGHT) {
			oRobot.oLeftMotor.iPower = 70;
			oRobot.oRightMotor.iPower = -70;
			/*} else  if(joy1Btn(4)) {
			oRobot.oLeftMotor.iPower = 40;
			oRobot.oRightMotor.iPower = 40;
			} else  if(joy1Btn(2)) {
			oRobot.oLeftMotor.iPower = -40;
			oRobot.oRightMotor.iPower = -40;*/
			} else {
			/* Set the drive power from the joysticks */
			oRobot.oLeftMotor.iPower = iJoyToPower(LEFT);
			oRobot.oRightMotor.iPower = iJoyToPower(RIGHT);
		}

		/* Give processor time to the other tasks */
		wait1Msec(JOYSTICK_UPDATE_TIME);
	}
}

/* Set manipulator data from the second joystick */
task ReadJoystick2() {
	wait1Msec(4);
	/* Run forever */
	while(1) {
		/* Gathers data from joysticks */
		getJoystickSettings(joystick);

		/* Sets the lifter's power from the arrow pad */
		oRobot.elevatorRightPower = 0;
		oRobot.elevatorLeftPower = 0;
		if(joystick.joy2_TopHat == DPAD_UP) {
			oRobot.elevatorRightPower = -60;
			oRobot.elevatorLeftPower = -60;
		}
		if(joystick.joy2_TopHat == DPAD_DOWN) {
			oRobot.elevatorRightPower = 35;
			oRobot.elevatorLeftPower = 35;
		}
//		oRobot.elevatorLeftPower = (float) (((float) joystick.joy2_y1) / 127) * 50;
//		oRobot.elevatorRightPower = (float) (((float) joystick.joy2_y2) / 127) * 50;
		/* Sets the power for the block dispenser from the arrow pad */
		oRobot.dispenserPower = 0;
		if(joystick.joy2_TopHat == DPAD_LEFT) {
			oRobot.dispenserPower = 100;
		}
		if(joystick.joy2_TopHat == DPAD_RIGHT) {
			oRobot.dispenserPower = -100;
		}
		/* Sets the power for the two grabber wheels */
		oRobot.grabberPower = 127;
		if(joy2Btn(6)) {
			oRobot.grabberPower = 255;
		}
		if(joy2Btn(8)) {
			oRobot.grabberPower = 0;
		}
		/* Sets power to the flippers based on joystick movement */
		oRobot.flipperPower = 127;
		if (joystick.joy2_y2 > 50){
			oRobot.flipperPower = 0;
			}else if (joystick.joy2_y2 < -50){
			oRobot.flipperPower = 255;
			}else{
			oRobot.flipperPower = 127;
		}
		/* Controls the elevator from the 5 and 7 buttons */
		oRobot.elevatorPower = 0;
		if(joy2Btn(5)) {
			oRobot.elevatorPower = 50;
		}
		if(joy2Btn(7)) {
			oRobot.elevatorPower = -50;
		}
		/* Controls the rotation of the drivetrain from both 4 buttons and both 2 buttons */
		/* It only would need to go down if there was a mechanical failure of some sort */
		oRobot.driveLifterPower = 0;
		if(joy2Btn(4) && joy2Btn(10)) {
			oRobot.driveLifterPower = -75;
		}
		if(joy2Btn(2) && joy2Btn(10)) {
			oRobot.driveLifterPower = 75;
		}
		/* Controls the lock from the 9 button */
		/* Requires both drivers to press it to try and prevent accidents */
		if(joy2Btn(9)) {
			oRobot.locked = false;
		}
		/* Controls the hooks from the 1 and 3 buttons */
		/* Unlike the other hanging things, this only requires one controller to hit it */
		/* This is for two reasons: Firstly raising the hooks is reversable */
		/* Secondly it dosen't risk disabling the robot like the other two hanging operations do */
		if(joy2Btn(1)){
			oRobot.hooks = false;
		}
		if(joy2Btn(3)){
			oRobot.hooks = true;
		}
		/* Give processor time to other tasks */
		wait1Msec(JOYSTICK_UPDATE_TIME);
	}
}

/* Update the driving hardware */
task UpdateDriveMotors() {
	/* Run forever */
	while(1) {
		/* Set the motors with the requested values */
		motor[driveLeft] = -1 * oRobot.oLeftMotor.iPower;
		motor[driveRight] = oRobot.oRightMotor.iPower;
		motor[motorA] = oRobot.oLeftMotor.iPower;

		/* Give processor time to other tasks */
		wait10Msec(MOTOR_UPDATE_TIME);
	}
}

/* Update the manipulator hardware */
task UpdateManipulators() {
	bool launched = false;
	wait1Msec(1);
	/* Run forever */
	while(1) {
		/* Set the manipulators with the requested values */
		servo[flipper] = oRobot.flipperPower;
		servo[leftGrabber] = oRobot.grabberPower;
		servo[rightGrabber] = abs(oRobot.grabberPower - 255);
		/* If its locked, stay in the standard position */
		/* If its unlockedd, move out of the way to allow the drivetrain to rotate */
		if (oRobot.locked == false){
			servo[driveLock] = 180;
			}else{
			servo[driveLock] = 0;
		}
		/* Sets various motor powers from the variables */
		motor[elevatorElevator] = oRobot.elevatorRightPower;
	//	motor[motorB] = oRobot.elevatorPower;
	//	motor[motorC] = oRobot.dispenserPower;
		motor[driveLifter] = oRobot.driveLifterPower;
		/* Checks if hooks need to be up, and lifts them */
		if(oRobot.hooks == true){
			servo[leftHanger] = 255;
			servo[rightHanger] = 0;
			}else{
			servo[leftHanger] = 35;
			servo[rightHanger] = 220;
		}
		/* Give processor time to other tasks */
		wait1Msec(MOTOR_UPDATE_TIME);
	}
}

/* Print debugging information */
task Debug() {
	/* Clear the screen so we can use it */
	disableDiagnosticsDisplay();

	/* Run forever */
	while(1) {
		/* Output the amount of power being sent to the drive motors */
		eraseDisplay();
		wait10Msec(1);
	}
}

/* Initialize the entire robot */
void vInitializeRobot() {
	/* Initialize the variables used by the file related functions */
	TFileHandle file;
	TFileIOResult result;
	byte value;

	/* Set all motors and servos to their initial positions */
	oRobot.oLeftMotor.iPower = 0;
	oRobot.oRightMotor.iPower = 0;
	oRobot.locked = true;
	oRobot.hooks = false;

	/* Read the driving mode from a file containing the desired mode, represented as an integer*/
	OpenRead(file, result, "teleoprc.txt", FILE_SIZE);
	ReadShort(file, result, value);
	Close(file,result);
	oRobot.oMode = (mode) (value - 48);

	return;
}

/* Calculates the motor power for a specific side based off the joystick value and drive mode */
int iJoyToPower(side theSide) {
	/* Initialize variables */
	float fLeftPower;
	float fRightPower;

	/* Choose the algorithm based off of the requested mode */
	switch(oRobot.oMode) {
		/* Linearly scaled tank mode */
	case TNK_LIN:
		fLeftPower = (float) (((float) joystick.joy1_y1) / 127);
		fRightPower = (float) (((float) joystick.joy1_y2) / 127);
		fLeftPower *= 100;
		fRightPower *= 100;
	fLeftPower = abs(fLeftPower) >= DEADZONE ? fLeftPower : 0;
	fRightPower = abs(fRightPower) >= DEADZONE ? fRightPower : 0;
		break;

		/* Exponentially scaled tank mode */
	case TNK_EXP:
		fLeftPower = (float) (((float) joystick.joy1_y1) / 127);
		fRightPower = (float) (((float) joystick.joy1_y2) / 127);
		pow(fLeftPower, 3);
		pow(fRightPower, 3);
		fLeftPower *= 100;
		fRightPower *= 100;
		break;

		/* Linearly scaled lowspeed tank mode */
	case TNK_LOW:
		fLeftPower = (float) (((float) joystick.joy1_y1) / 127);
		fRightPower = (float) (((float) joystick.joy1_y2) / 127);
		fLeftPower *= 50;
		fRightPower *= 50;
	fLeftPower = abs(fLeftPower) >= DEADZONE ? fLeftPower : 0;
	fRightPower = abs(fRightPower) >= DEADZONE ? fRightPower : 0;
		break;

		/* Linearly scaled arcade mode */
	case ARC_LIN:
		if(abs(joystick.joy1_y1) > DEADZONE) {
			fLeftPower = 100 * ((float) (((float) joystick.joy1_y1) / 127));
			fRightPower = 100 * ((float) (((float) joystick.joy1_y1) / 127));
			} else if(abs(joystick.joy1_x2) > DEADZONE) {
			fLeftPower = 100 * ((float) (((float) joystick.joy1_x2) / 127));
			fRightPower = -100 * ((float) (((float) joystick.joy1_x2) / 127));
			} else {
			fLeftPower = 0;
			fRightPower = 0;
		}
		break;

		/* Exponentially scaled arcade mode */
	case ARC_EXP:
		if(abs(joystick.joy1_y1) > DEADZONE) {
			fLeftPower = (float) (((float) joystick.joy1_y1) / 127);
			fRightPower = (float) (((float) joystick.joy1_y1) / 127);
			pow(fLeftPower, 3);
			pow(fRightPower, 3);
			fLeftPower *= 100;
			fRightPower *= 100;
			} else if(abs(joystick.joy1_x2) > DEADZONE) {
			fLeftPower = (float) (((float) joystick.joy1_x2) / 127);
			fRightPower = (float) (((float) joystick.joy1_x2) / 127);
			pow(fLeftPower, 3);
			pow(fRightPower, 3);
			fLeftPower *= 100;
			fRightPower *= -100;
			} else {
			fLeftPower = 0;
			fRightPower = 0;
		}
		break;

		/* Linearly scaled lowspeed arcade mode */
	case ARC_LOW:
		if(abs(joystick.joy1_y1) > DEADZONE) {
			fLeftPower = 50 * ((float) (((float) joystick.joy1_y1) / 127));
			fRightPower = 50 * ((float) (((float) joystick.joy1_y1) / 127));
			} else if(abs(joystick.joy1_x2) > DEADZONE) {
			fLeftPower = 50 * ((float) (((float) joystick.joy1_x2) / 127));
			fRightPower = -50 * ((float) (((float) joystick.joy1_x2) / 127));
			} else {
			fLeftPower = 0;
			fRightPower = 0;
		}
		break;

		/* Somehow we have a garbled drive mode, or the file wasn't there to be opened */
	default:
		/* If this happens we set the drive mode to the simplest one, linear scaled tank mode */
		oRobot.oMode = TNK_LIN;
		PlaySound(soundBeepBeep);
	}

	/* Return the requested value */
	switch(theSide) {
	case LEFT:
		return (int) fLeftPower;
		break;

	case RIGHT:
		return (int) fRightPower;
		break;

		/* Somehow we have a garbled drive mode; don't move! */
	default:
		PlaySound(soundBeepBeep);
		return 0;
	}
}
